Update automatically generated files
Signed-off-by: Tobias Toedter <t.toedter@gmx.net>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3881,16 +3881,26 @@ fi
 
 
 if test -n "$PKG_CONFIG"; then
-  vers=`$PKG_CONFIG --modversion libxml++-2.6 2>/dev/null | awk 'BEGIN { FS = "."; } { printf "%d", ($1 * 1000 + $2) * 1000 + $3;}'`
-  if test -n "$vers" && test "$vers" -ge 2006000
-  then
-     LIBXML_LIBS="-lxml++-2.6"
-     LIBXML_CFLAGS="`$PKG_CONFIG --cflags libxml++-2.6`"
-  else
-     { { echo "$as_me:$LINENO: error: You need at least libxml++ 2.6.0" >&5
+	{ echo "$as_me:$LINENO: checking if libxml++ version is greater than 2.6.0" >&5
+echo $ECHO_N "checking if libxml++ version is greater than 2.6.0... $ECHO_C" >&6; }
+	vers=`$PKG_CONFIG --modversion libxml++-2.6 2>/dev/null | awk 'BEGIN { FS = "."; } { printf "%d", ($1 * 1000 + $2) * 1000 + $3;}'`
+	if test -n "$vers" && test "$vers" -ge 2006000
+	then
+		LIBXML_LIBS="-lxml++-2.6"
+		LIBXML_CFLAGS="`$PKG_CONFIG --cflags libxml++-2.6`"
+		{ echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }
+	else
+		{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+		{ { echo "$as_me:$LINENO: error: You need at least libxml++ 2.6.0" >&5
 echo "$as_me: error: You need at least libxml++ 2.6.0" >&2;}
    { (exit 1); exit 1; }; }
-  fi
+	fi
+else
+	{ { echo "$as_me:$LINENO: error: pkg-config is required to build this program" >&5
+echo "$as_me: error: pkg-config is required to build this program" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 
@@ -6717,7 +6727,7 @@ fi
 
 
 if test -z "$PO4A"; then
-    { { echo "$as_me:$LINENO: error: po4a is required to build this program" >&5
+	{ { echo "$as_me:$LINENO: error: po4a is required to build this program" >&5
 echo "$as_me: error: po4a is required to build this program" >&2;}
    { (exit 1); exit 1; }; }
 fi
