Trim down linked in libraries and upgrade AC_MSG_WARN to AC_MSG_ERROR

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3883,11 +3883,12 @@ if test -n "$PKG_CONFIG"; then
   vers=`$PKG_CONFIG --modversion libxml++-2.6 2>/dev/null | awk 'BEGIN { FS = "."; } { printf "%d", ($1 * 1000 + $2) * 1000 + $3;}'`
   if test -n "$vers" && test "$vers" -ge 2006000
   then
-     LIBXML_LIBS="`$PKG_CONFIG --libs libxml++-2.6`"
+     LIBXML_LIBS="-lxml++-2.6"
      LIBXML_CFLAGS="`$PKG_CONFIG --cflags libxml++-2.6`"
   else
-     { echo "$as_me:$LINENO: WARNING: You need at least libxml++ 2.6.0" >&5
-echo "$as_me: WARNING: You need at least libxml++ 2.6.0" >&2;}
+     { { echo "$as_me:$LINENO: error: You need at least libxml++ 2.6.0" >&5
+echo "$as_me: error: You need at least libxml++ 2.6.0" >&2;}
+   { (exit 1); exit 1; }; }
   fi
 fi
 
